# Aanvullende velden die we binnen de website gebruiken
#
# Voor Schema.org
organization_name = "NLUUG"

organization_sameas = [
    "https://nluug.social/@nluug",
    "https://twitter.com/nluug",
    "https://www.wikidata.org/wiki/Q2137723",
]

keywords = [
    "DevOps",
    "Informatiebeveiliging",
    "Linux",
    "Open data",
    "Open source",
    "Open standaarden",
    "Privacy"
]

### Algemeen
description = "NLUUG website met de doelstellingen, laatste nieuws en evenementen van onze vereniging."

# Fallback-auteur voor posts die geen echte auteur hebben
#author = "NLUUG"

# Datum-formaat en tijdzone, de gebruikte waardes in datum en tijd zijn van belang
dateFormat = "02-01-2006"
timeZone = "Europe/Amsterdam"

### Grafisch
# TODO - vervangen van logo door icon
logo = "/assets/favicon.ico"

# Logo op normale weergave
logoNormal = "/afbeeldingen/logo/nluug-logo.png"

# Logo gebruikt in Schema.org (Organization)
logoHiRes="/afbeeldingen/logo/nluug-logo-high-resolution.jpg"

# Grootte van iconen (SVG-bestanden) zoals van social media
smallIconSize = 16
mediumIconSize = 32

# Kanarie: Deze tekst (en vogel) gebruiken we om lege waardes op te sporen in output
textNoTitle = "Geen titel 🐦"
textEmptyValue = "Geen waarde 🐦"

# Social
mastodon_instance = "https://nluug.social/"
mastodon_handle = "nluug"

# EOF
