# Menu-configuratie

  [[main]]
    identifier = "organisatie"
    name = "Organisatie"
    pageRef = "/organisatie"
    weight = 10

  [[main]]
    identifier = "organisatie-goals"
    name = "Doelstellingen"
    url = "/organisatie/doelstellingen/"
    parent = "organisatie"
    weight = 11

  [[main]]
    identifier = "organisatie-bestuur"
    name = "Bestuur"
    url = "/organisatie/bestuur/"
    parent = "organisatie"
    weight = 12

  [[main]]
    identifier = "organisatie-commissies"
    name = "Commissies"
    url = "/organisatie/commissies/"
    parent = "organisatie"
    weight = 13

  [[main]]
    identifier = "nluug-award"
    name = "NLUUG Award"
    url = "/organisatie/nluug-award/"
    parent = "organisatie"
    weight = 14

  [[main]]
    identifier = "evenementen"
    name = "Evenementen"
    url = "/evenementen/"
    weight = 20

  [[main]]
    identifier = "evenementen-kalender"
    name = "Kalender"
    url = "/evenementen/kalender/"
    parent = "evenementen"
    weight = 21

  [[main]]
    identifier = "evenementen-nluug"
    name = "NLUUG"
    url = "/evenementen/nluug/"
    parent = "evenementen"
    weight = 22

  [[main]]
    identifier = "evenementen-sprekers"
    name = "Sprekers"
    url = "/evenementen/sprekers/"
    parent = "evenementen"
    weight = 23

  [[main]]
    identifier = "lidmaatschap"
    name = "Lidmaatschap"
    url = "/lidmaatschap/"
    weight = 30

  [[main]]
    identifier = "lidmaatschap-aanmelden"
    name = "Aanmelden"
    url = "/lidmaatschap/aanmelden/"
    parent = "lidmaatschap"
    weight = 31

  [[main]]
    identifier = "lidmaatschap-ereleden"
    name = "Ereleden"
    url = "/lidmaatschap/ereleden/"
    parent = "lidmaatschap"
    weight = 32

  [[main]]
    identifier = "lidmaatschap-ledendeel"
    name = "Inloggen voor leden"
    url = "https://leden.nluug.nl/leden/"
    parent = "lidmaatschap"
    weight = 34

  [[main]]
    identifier = "nieuws"
    name = "Nieuws"
    url = "/nieuws/"
    weight = 40

  [[main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 50

  [[footer]]
    identifier = "voorwaarden"
    name = "Algemene Voorwaarden"
    pageRef = "/algemene-voorwaarden/"
    weight = 10

  [[footer]]
    identifier = "privacy"
    name = "Privacy"
    pageRef = "/privacy/"
    weight = 20

# EOF
